const ACTIONS = {
    SUCCESS_MESSAGE: 'SUCCESS_MESSAGE',
    ERROR_MESSAGE: 'ERROR_MESSAGE',
    ARTICLES: 'ARTICLES',
    FETCH_USER_DETAILS: 'FETCH_USER_DETAILS',
    SOURCES: 'SOURCES',
    ALL_SOURCES: 'ALL_SOURCES'
}

export default ACTIONS;